# Generated by Django 5.0.6 on 2024-10-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_alter_leaderboard_score_alter_leaderboard_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='achievements',
        ),
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='gameplay.achievement'),
        ),
    ]
