# Generated by Django 5.0.6 on 2024-10-28 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_alter_leaderboard_score_alter_leaderboard_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelevel',
            name='grid_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='word_length',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('current_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameplay.word')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.gamelevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
